[2022-11-29T17:59:29.102+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2022-11-29T17:59:29.129+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_dag.etlPlaces scheduled__2022-11-29T17:58:25.034163+00:00 [queued]>
[2022-11-29T17:59:29.150+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_dag.etlPlaces scheduled__2022-11-29T17:58:25.034163+00:00 [queued]>
[2022-11-29T17:59:29.152+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:59:29.153+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T17:59:29.154+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:59:29.180+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): etlPlaces> on 2022-11-29 17:58:25.034163+00:00
[2022-11-29T17:59:29.189+0000] {standard_task_runner.py:54} INFO - Started process 5266 to run task
[2022-11-29T17:59:29.197+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'etlPlaces', 'scheduled__2022-11-29T17:58:25.034163+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmptrwua43r']
[2022-11-29T17:59:29.200+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask etlPlaces
[2022-11-29T17:59:29.203+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/etl_dag.py
[2022-11-29T17:59:29.960+0000] {task_command.py:384} INFO - Running <TaskInstance: etl_dag.etlPlaces scheduled__2022-11-29T17:58:25.034163+00:00 [running]> on host 2c28799c9ef4
[2022-11-29T17:59:29.970+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2022-11-29T17:59:30.153+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=etlPlaces
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T17:58:25.034163+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T17:58:25.034163+00:00
[2022-11-29T17:59:30.159+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_places.py", line 8, in etl_places
    df = extract()
  File "/opt/airflow/dags/etl_places.py", line 14, in extract
    places = pd.read_csv('geoplaces2.csv',usecols=["placeID","name","city"])
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1729, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 857, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'geoplaces2.csv'
[2022-11-29T17:59:30.181+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2022-11-29T17:59:30.193+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=etlPlaces, execution_date=20221129T175825, start_date=20221129T175929, end_date=20221129T175930
[2022-11-29T17:59:30.219+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 10 for task etlPlaces ([Errno 2] No such file or directory: 'geoplaces2.csv'; 5266)
[2022-11-29T17:59:30.261+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-29T17:59:30.311+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
