[2022-11-29T17:57:29.581+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2022-11-29T17:57:29.603+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_dag.etlPlaces scheduled__2022-11-29T17:56:25.034163+00:00 [queued]>
[2022-11-29T17:57:29.626+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_dag.etlPlaces scheduled__2022-11-29T17:56:25.034163+00:00 [queued]>
[2022-11-29T17:57:29.628+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:57:29.629+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T17:57:29.631+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:57:29.661+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): etlPlaces> on 2022-11-29 17:56:25.034163+00:00
[2022-11-29T17:57:29.669+0000] {standard_task_runner.py:54} INFO - Started process 5191 to run task
[2022-11-29T17:57:29.678+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'etlPlaces', 'scheduled__2022-11-29T17:56:25.034163+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpthdp2ne7']
[2022-11-29T17:57:29.680+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask etlPlaces
[2022-11-29T17:57:29.683+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/etl_dag.py
[2022-11-29T17:57:30.681+0000] {task_command.py:384} INFO - Running <TaskInstance: etl_dag.etlPlaces scheduled__2022-11-29T17:56:25.034163+00:00 [running]> on host 2c28799c9ef4
[2022-11-29T17:57:30.690+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2022-11-29T17:57:30.876+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=etlPlaces
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T17:56:25.034163+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T17:56:25.034163+00:00
[2022-11-29T17:57:30.881+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_places.py", line 8, in etl_places
    df = extract()
TypeError: extract() missing 1 required positional argument: 'c'
[2022-11-29T17:57:30.905+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2022-11-29T17:57:30.925+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=etlPlaces, execution_date=20221129T175625, start_date=20221129T175729, end_date=20221129T175730
[2022-11-29T17:57:30.990+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 6 for task etlPlaces (extract() missing 1 required positional argument: 'c'; 5191)
[2022-11-29T17:57:31.058+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-29T17:57:31.157+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
